# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Role.all.length != 4
  Role.create!(role: "dps")
  Role.create!(role: "tank")
  Role.create!(role: "support")
  Role.create!(role: "none")
end

roles_hash = {
  "Abathur" => 3,
  "Anub\'arak" => 2,
  "Arthas" => 2,
  "Azmodan" => 1,
  "Brightwing" => 3,
  "Chen" => 2,
  "Diablo" => 2,
  "E.T.C." => 2,
  "Falstad" => 1,
  "Gazlowe" => 1,
  "Illidan" => 1,
  "Jaina" => 1,
  "Johanna" => 2,
  "Kael\'thas" => 1,
  "Kerrigan" => 1,
  "Leoric" => 2,
  "Li Li" => 3,
  "Malfurion" => 3,
  "Muradin" => 2,
  "Murky" => 1,
  "Nazeebo" => 1,
  "Nova" => 1,
  "Raynor" => 1,
  "Rehgar" => 3,
  "Sgt. Hammer" => 1,
  "Sonya" => 2,
  "Stitches" => 2,
  "Sylvanas" => 1,
  "Tassadar" => 3,
  "The Butcher" => 1,
  "The Lost Vikings" => 1,
  "Thrall" => 1,
  "Tychus" => 1,
  "Tyrael" => 2,
  "Tyrande" => 3,
  "Uther" => 3,
  "Valla" => 1,
  "Zagara" => 1,
  "Zeratul" => 1
}

roles_hash.each do |hero_name, role|
  Hero.find_by_name(hero_name).update_attribute(:role_id, role)
end

attr_hash = {
  "Abathur" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Anub\'arak" => {
       "Tankability" => 0.7,
       "Crowd Control" => 0.5,
       "Healing" => 0.0,
       "Lane Presence" => 0.4,
       "Damage" => 0.4,
       "Pushing" => 0.4,
     },
  "Arthas" => {
       "Tankability" => 0.7,
       "Crowd Control" => 0.6,
       "Healing" => 0.2,
       "Lane Presence" => 0.5,
       "Damage" => 0.5,
       "Pushing" => 0.6,
     },
  "Azmodan" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Brightwing" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Chen" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Diablo" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "E.T.C." => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Falstad" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Gazlowe" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Illidan" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Jaina" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Johanna" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Kael\'thas" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Kerrigan" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Leoric" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Li Li" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Malfurion" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Muradin" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Murky" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Nazeebo" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Nova" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Raynor" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Rehgar" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Sgt. Hammer" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Sonya" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Stitches" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Sylvanas" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Tassadar" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "The Butcher" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "The Lost Vikings" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Thrall" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Tychus" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Tyrande" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Tyrael" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Uther" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Valla" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Zagara" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  "Zeratul" => {
       "Tankability" => 0.1,
       "Crowd Control" => 0.1,
       "Healing" => 0.3,
       "Lane Presence" => 0.8,
       "Damage" => 0.5,
       "Pushing" => 0.8,
     },
  }

attr_hash.each do |hero_name, attr|
  Hero.find_by_name(hero_name).update_attribute(:attr, attr)
end
