# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Role.all.length != 4
  Role.create!(role: "dps")
  Role.create!(role: "tank")
  Role.create!(role: "support")
  Role.create!(role: "none")
end

roles_hash = {
  "Abathur" => 3,
  "Anub\'arak" => 2,
  "Arthas" => 2,
  "Azmodan" => 1,
  "Brightwing" => 3,
  "Chen" => 2,
  "Diablo" => 2,
  "E.T.C." => 2,
  "Falstad" => 1,
  "Gazlowe" => 1,
  "Illidan" => 1,
  "Jaina" => 1,
  "Johanna" => 2,
  "Kael\'thas" => 1,
  "Kerrigan" => 1,
  "Leoric" => 2,
  "Li Li" => 3,
  "Malfurion" => 3,
  "Muradin" => 2,
  "Murky" => 1,
  "Nazeebo" => 1,
  "Nova" => 1,
  "Raynor" => 1,
  "Rehgar" => 3,
  "Sgt. Hammer" => 1,
  "Sonya" => 2,
  "Stitches" => 2,
  "Sylvanas" => 1,
  "Tassadar" => 3,
  "The Butcher" => 1,
  "The Lost Vikings" => 1,
  "Thrall" => 1,
  "Tychus" => 1,
  "Tyrael" => 2,
  "Tyrande" => 3,
  "Uther" => 3,
  "Valla" => 1,
  "Zagara" => 1,
  "Zeratul" => 1
}

roles_hash.each do |hero_name, role|
  Hero.find_by_name(hero_name).update_attribute(:role_id, role)
end

attr_hash = {
  "Abathur" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Anub\'arak" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Arthas" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Azmodan" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Brightwing" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Chen" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Diablo" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "E.T.C." => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Falstad" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Gazlowe" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Illidan" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Jaina" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Johanna" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Kael\'thas" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Kerrigan" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Leoric" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Li Li" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Malfurion" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Muradin" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Murky" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Nazeebo" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Nova" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Raynor" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Rehgar" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Sgt. Hammer" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Sonya" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Stitches" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Sylvanas" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Tassadar" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "The Butcher" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "The Lost Vikings" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Thrall" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Tychus" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Tyrande" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Tyrael" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Uther" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Valla" => '[
       {axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
     ]',
  "Zagara" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  "Zeratul" => [
       '{axis:"Tankability", value: 0.5},
       {axis:"Crowd Control", value: 0.5},
       {axis:"Healing", value: 0.5},
       {axis:"Lane Presence", value: 0.5},
       {axis:"Damage", value: 0.5},
       {axis:"Pushing", value: 0.5},
    ]',
  }
